# Generated by Django 5.2.8 on 2025-12-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PotaId', models.IntegerField()),
                ('PotaSize', models.CharField(max_length=200)),
                ('PotaCost', models.DecimalField(decimal_places=4, max_digits=10)),
                ('PotaBirth', models.DateField()),
                ('PotaName', models.CharField(max_length=200)),
            ],
        ),
    ]
