# Generated by Django 5.2.8 on 2025-12-13 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potareg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pota',
            name='PotaId',
        ),
    ]
