# Generated by Django 5.2.8 on 2025-12-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potareg', '0002_remove_pota_potaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pota',
            name='PotaCost',
            field=models.IntegerField(),
        ),
    ]
